pool:
  vmImage: 'Ubuntu 16.04'

variables:
  image: 'reward'
  latestTag: '$(image):latest'

steps:
- script: |
    docker build -t $(dockerId).azurecr.io/$(latestTag) --build-arg port=80 .
    docker login -u $(dockerId) -p $(pswd) $(dockerId).azurecr.io
    docker push $(dockerId).azurecr.io/$(latestTag)
  displayName: 'Build and push Docker image'
